# Generated by Django 4.0.4 on 2022-04-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=2500, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, max_length=5000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_flag', models.BooleanField(default=False)),
                ('option_status', models.BooleanField(default=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
