# Generated by Django 3.1.4 on 2022-04-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220425_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizdetail',
            old_name='user_answer',
            new_name='user_answer_id',
        ),
    ]
