# Generated by Django 3.1.4 on 2022-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220425_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsummary',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
