# Generated by Django 3.1.4 on 2022-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220426_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsummary',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
